### ISSUE TITLE
Allow tagging while the video is paused

### ISSUE THREAD

**Issue by Campagne20** [cxam/tagx#5]
Greetings,

I am reaching out, because I have a couple of questions in regards to your application.

The first question is, how can I be able to make shareable links private, to where only certain individuals can view the video?

Also, would you like to alter the UI you all offer and cater it to more what I'm looking for, specifically to make tagging easier and more in-depth buttons? I'm looking to tag a basketball game for the different actions that occur during the game, and specify which athlete committed the action.

If you guys could offer any advice, it would be greatly appreciated!

Thanks,
Jazz Felton

Campagne 20

**Comment by cxam** [comment]
Thanks for getting in touch @Campagne20, I've addressed your questions below.

1. You can make private links by clicking on the **Share** button just under the player. You will see a modal that has an another button named **Short Link**. Clicking on this will generate a unique and unguessable link to your video, which you can share privately. Take a note of the key that it provides if you wish to edit  this video in the future. Please see the **Share** section on this link for some information on this feature: https://tagx.io/support/interfaces/video

2. The tagging UI is pretty customisable and your use case would be a perfect example for the use of this service. There are many was you could setup the UI to do what you're asking and there is an example setup of this on site ([here](https://tagx.io/video/youtube/PNvLxIZO54U/@default_tab:tracks/Goals:%20Real%20Madrid@tag_lag_time:0:05/Goals:%20Liverpool@tag_lag_time:0:05/1:00:13-1:00:28@track:1@name:Karim%20Benzema,1:04:30-1:04:45@track:2@name:Sadio%20Man%C3%A9@note:Assisted%3A%20Dejan%20Lovren,1:13:05-1:13:20@track:1@name:Gareth%20Bale@note:Assisted%3A%20Marcelo,1:32:46-1:33:01@track:1@name:Gareth%20Bale@note:Assisted%3A%20Marcelo?show_empty_tracks=false)). This is in a football context but I'd imagine the setup would be similar. 

Following is an example of how your setup could work. Create a [**Track**](https://tagx.io/support/interfaces/tracks) for each of the different actions (Pass, Shoot, etc) or depending on how in-depth you want to record these actions (Bounce pass, Fadeaway, etc). As you play through the video, you can click on the buttons generated under the video or use [**Hotkeys**](https://tagx.io/support/advanced/hotkeys) to tag easier. To specify which athlete committed the action, you can do this in two ways. Create a track for each athlete and copy/duplicate the the tags from the other action tracks. To do this, you would click on the tracks tab, click on the tag (three dots) you wish to duplicate, edit track and select one or more tracks to copy to. Alternatively, for each tag, you can [edit](https://tagx.io/support/interfaces/tags) and provide a name or description. This is how it's done on the example link above. Both these would require a second pass where (1) tag the main actions (2) go through all the tags and copy/duplicate or specific name/description. You could also do this in a single pass if you pause the video after each tag.

I appreciate any feedback you have on improving this process, so if you have anything in mind about how the UI could be altered and make tagging easier for your use case then let me know.

**Comment by Campagne20** [comment]
Thanks for all the help/info!

A dope feature I would like, is to be able to tag the video, while its paused. So time stamp where the video is currently in, while the video is paused. Would be a huge help for me!

**Comment by cxam** [comment]
There were some edge cases with YouTube when it's in a paused state and I decided at the time to make sure the video is playing before a tag is created. However, I can see the ability to tag while paused would make it a lot easier, specially if you want to create tags across multiple tracks and have the time in sync.

I have pushed an update live with a fix that would now allow you to tag while paused, without the edge cases experienced before. You should see **v0.3.0** in the footer after a refresh. Thanks for the suggestion!

**Comment by Campagne20** [comment]
Thank you for that! Has been a huge help!

**Comment by Campagne20** [comment]
Is there a way to save the clips, I have been scared to click out the tab?

**Comment by cxam** [comment]
@Campagne20 do you mean all the tagging? If so, you can either:

1. Bookmark the page and/or copy the link from the address bar and save it somewhere yourself. Visiting that specific url will load everything up again.
2. Save it as a short link using the **Share** feature (keeping a note of the **Key** it provides so you can edit it later). This might be the better way to do it as it will give you a shorter link.

**Comment by Campagne20** [comment]
Great! Just wanted to be sure that was the best way. 

Thanks

**Comment by cxam** [comment]
No problem! I've update this issue title and will close it as complete. If you have any other questions or feature requests then just create another one, thanks.
