### ISSUE TITLE
Automatic create tags for 10 seconds "prior" to current time

### ISSUE THREAD

**Issue by kevinkuan0** [cxam/tagx#6]
Hi, drawing inspiration from other apps, I think it is best if we create automatic tags based on what we've already watched. So the user do not need to scroll back the video before highlighting, but rather highlight during the first time read.

Example use case: 
The speaker in the video just said something an interesting quote.
Use clicks "highlight 10 seconds prior" button to capture that quote. video continues to play.

Note: We could create three buttons with different duration. The duration could be changed in settings.
"Highlight 10 seconds prior"
"Highlight 1 minute prior"
"Highlight 5 minutes prior"

**Comment by cxam** [comment]
Thanks for the feedback. This is already possible by creating a **[Track](https://tagx.io/support/interfaces/tracks)** with a lag time. Here is an example video demonstrating the ability for your use case: https://tagx.io/video/id/9VIDdHa6uXZKm4jeiVadB

![image](https://user-images.githubusercontent.com/7763217/108593503-f8ee6500-736b-11eb-81ee-85f47e8f104a.png)
